### ISSUE TITLE
install.md

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#1]
It would be nice to have a lab showing how to install cryptol, saw, hard dependency z3, and extra smt solvers yices, cvc4, and abc.

This [.travis.yml](https://github.com/weaversa/saw-demos/blob/master/.travis.yml) file shows how to install most of the tools for OSX and Ubuntu. So, it might be useful to have as a starting point when writing this lab.

**Comment by WeeknightMVP** [comment]
@weaversa We should add the `--rm` option to `docker run` instructions; otherwise, old containers persist and need to be removed later via `docker prune` or `docker rm`.

**Comment by weaversa** [comment]
I don’t actually know anything about docker. If you know that some flag should be there, please make the PR and I’ll approve it.
