### ISSUE TITLE
Cryptol Style Guide

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#10]
Many people recommend this style guide for Haskell --- https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md

Since Cryptol does look a lot like Haskell, It might be a good starting place. I found it easy to read and easily see how it would apply to Cryptol specs.

Thoughts?

**Comment by weaversa** [comment]
I really like the idea of this course having a style guide. If you're going to learn Cryptol, why not learn to make it look nice. I'll start a new branch and open a pull request. Then we can all work on one together.

**Comment by AssemblyZig** [comment]
Include guidance on use of parens or other grouping to make code more readable.
