### ISSUE TITLE
`CryptoProofs` and reusability

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#101]
(_Edited_ to rename `g` to `f'` in `inverts` to reflect that `f` and `f'` are related.)

In lieu of repeatedly defining inverse and injectivity properties for ciphers every time, I find it helpful to define generic properties:

```cryptol
module CommonProperties where

/**
 * `f` is _injective_ iff it maps distinct elements of its domain `d`
 * to distinct elements of its range `r`
 */
injective:
     {d, r} (Cmp d, Cmp r) => (d -> r) -> d -> d -> Bit
injective f x x' =
     x != x' ==> f x != f x'

/**
 * `f'` _inverts_ `f` iff when `f` maps `x` to `y`, 
 * `f'` maps `y` back to `x`.
 */
inverts:
    {d, r} Cmp d => (r -> d) -> (d -> r) -> d -> Bit
inverts f' f x =
    f' (f x) == x
```

Then for a particular block cipher:

```cryptol
import CommonProperties (injective, inverts)

noncollision: Key -> Block -> Block -> Bit
property noncollision key = injective (encrypt key)

recovery: Key -> Block -> Bit
property recovery key = inverts (decrypt key) (encrypt key)
```

`CryptoProofs` might be a good place to add these, as well as spiels on generic properties and reuse.  It's good to cover lambda functions as well, but we can't reuse those...

**Comment by weaversa** [comment]
Some of the labs ask the students to come up with these as exercises, don't they? This kind of module seems like a good fit for cryptol-specs. I'm worried this level of abstraction would confuse new students.

**Comment by WeeknightMVP** [comment]
It would lessen the confusion to relate lambda functions to named ones, especially where such an association produces value.

**Comment by WeeknightMVP** [comment]
We copy parts of [cryptol-specs](https://github.com/GaloisInc/cryptol-specs), but don't mention it anywhere in the course...

**Comment by weaversa** [comment]
Learning lambda functions is part of the course.

**Comment by weaversa** [comment]
`:prove \k pt -> inverts (encrypt key) (decrypt key) pt`
vs
`:prove \k pt -> decrypt key (encrypt key pt) == pt`

I think, when learning, writing it out (potentially over and over is good. Repetition is important when learning new concepts. Especially when the thing you're writing out is shorter than the abstraction.

**Comment by WeeknightMVP** [comment]
``\`key``

The first command can be shortened to `:prove \key -> inverts (decrypt key) (encrypt key)`:

```shell
> :prove \key -> inverts (decrypt key) (encrypt key)
> :prove \key pt -> decrypt key (encrypt key pt) == pt
```

I agree that repetition is important, but would also rather not dismiss that functions are first-class values in Cryptol, much like they are in Python or (in more advanced usage by way of function pointers) C.

To introduce functions as values while affording students an opportunity to practice important properties on specific applications through repetition, perhaps we could introduce an optional follow-up to `CryptoProofs` that introduces functions-as-values and revisits injectivity, inversion, and any other common properties.  The (optional) lab on transposition ciphers could then apply these in the context of permutations (e.g. that a permutation can be inverted to recall the original sequence order, and such a permutation is injective) in a generic background before introducing Rail Fence.  I'll try to update that branch in the next day or two for review.

**Comment by weaversa** [comment]
That’s a good plan. Eventually, these extra labs could get their own track In an advanced course.

**Comment by weaversa** [comment]
Closing since this was added to the transposition lab.
