### ISSUE TITLE
Podman / SELinux

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#121]
CentOS 8 eschews Docker in favor of RedHat's [Podman](https://podman.io/), an alternative preconfigured to work with SELinux without root privileges to run containers.  Many Docker commands are directly mirrored by Podman (e.g. `docker pull galoisinc/cryptol:latest` becomes `podman pull galoisinc/cryptol:latest`), but VS Code support is spotty: you can [change the Remote Containers plugin's settings](https://code.visualstudio.com/docs/remote/containers#_can-i-use-podman-instead-of-docker) to call `podman` instead of `docker`, [alias docker to podman](https://podman.io/whatis.html), or [install a package that does this for you](https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/), but commands like `Open workspace in container` don't work, and Docker Compose isn't (directly) supported.  `Build container`, `Open in container`, etc. are _supposed_ to work, but for some reason are returning an error code in my CentOS 8 VM.

Speaking of SELinux, in unprivileged Podman or Docker environments where SELinux is enforced, one needs to specify [SELinux volume mount option](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) `z` (shared) or `Z` (private); otherwise, the mounted directory will be inaccessible in the container.  Because `--mount` [does not support these](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag), such cases will require `-v` instead, e.g. `docker run --rm -it --read-only -v ${pwd}:/mnt/cryptol-course:z --env CRYPTOLPATH=/mnt/cryptol-course galoisinc/cryptol:latest`.

Perhaps we should amend `INSTALL.md` to this effect...

**Comment by jdwoolc** [comment]
This sounds, partially, like an issue that could be communicated to the VSCode Remote Container maintainers. They may be able to integrate better support for alternative containerization directly in VSCode.

**Comment by jpziegler** [comment]
> Podman 1.9+ is mostly compatible with Docker's CLI commands and therefore generally does work if you update the setting Remote > Containers: Docker Path to podman on Linux.

https://code.visualstudio.com/docs/remote/containers

**Comment by weaversa** [comment]
I'm feeling like, now that GitPod works, and VS Code (and modern OSes) have good support for Docker, these OS specific courses of action can be left to individual users to figure out. Folks can always create an issue if they have trouble.
