### ISSUE TITLE
Add outline numbers to digraph boxes

### ISSUE THREAD

**Issue by Reformated** [weaversa/cryptol-course#126]
For the benefit of students going between the README.md course outline ("lab order") and digraph ("Graphical view of the course"), I recommend adding outline numbers to the text boxes in the graph.

**Comment by WeeknightMVP** [comment]
How would optional modules be numbered (or lettered)?

**Comment by Reformated** [comment]
Fair question.  I'm not sure those need numbers, but I'd be inclined to say if there are two optional items under outline number 4, then just call them 4a and 4b (and maybe include the word optional, although the black arrows imply that), even if they do not have to be done in a particular order, but the arrows imply that.
