### ISSUE TITLE
Overview of Cryptol (Lab)

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#14]
This course needs a lab focusing on an overview of Cryptol. There is some information in [some old slides](/weaversa/cryptol-course/tree/disused-lavatory/old/cryptol-in-n-minutes/)

**Comment by jdwoolc** [comment]
I'm going to take a stab at getting this started -- will focus on building examples to follow the referenced PDF and also some exposition.

**Comment by jdwoolc** [comment]
Working on this today -- check out the overview branch if you're interested.

**Comment by jdwoolc** [comment]
I think it make sense to either begin or end the overview with a course outline or a suggested pathway through key modules *a la* Software Foundations course. This may depend on fleshing out the rest of the materials a bit.

**Comment by weaversa** [comment]
How about we let the README.md for the entire repo have that information? That way the overview lab can point to there, and we can update the README as we add/remove/modify labs.

**Comment by jdwoolc** [comment]
Sounds good. I made a commit with something I'd consider a solid "first draft" (modulo proofreading, etc...).

**Comment by weaversa** [comment]
Great work!!!! I'll make a review!
