### ISSUE TITLE
Transposition Ciphers prereqs

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#140]
As @WeeknightMVP pointed out in #99, we still need to add (look over) the prereqs sections for these new labs.

**Comment by WeeknightMVP** [comment]
A student recently pointed out that [`rearrange`](https://github.com/weaversa/cryptol-course/blame/fa7ac56cf3ceef783436c179005804e8c43ab1be/labs/Transposition/Transposition.md#L349-L361) uses a multi-branch `if` statement, which is not covered earlier; this should be added to the [appropriate section](https://github.com/weaversa/cryptol-course/blame/fa7ac56cf3ceef783436c179005804e8c43ab1be/labs/Language/Basics.md#L1577) in `Language/Basics`.

**Comment by WeeknightMVP** [comment]
I'm OK with the `Transposition(Answers).md` pages laying these out and saying "...and later modules apply these concepts to various transposition ciphers."
