### ISSUE TITLE
Layer Cake

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#143]
Adding "breadcrumbs" to the main modules is helpful in ushering along course participants, but for some of the optional labs with multiple Cryptol modules (Cryptol and SAW Demos, Salsa20, etc.), it seems abrupt to go from enjoying a Caesar demo to rushing along to Salsa20, for example.  The Transposition lab has the opposite problem, where participants have to go through all the different ciphers before getting to the Capstone lab.  Perhaps there should be multiple layers of navigation: one to traverse multiple modules of a lab, and another to traverse the labs, perhaps with additional links to optional labs where applicable.  Navigation is an interesting problem...

**Comment by weaversa** [comment]
I agree we should do this.

**Comment by AssemblyZig** [comment]
I played at integrating navigation links a few weeks back, using the markup
link mechanism. The results were annoying at best: relative links were
interpreted differently in straight browsing and in the GitHub interface.

Cheers,
Zig

**Comment by weaversa** [comment]
It's likely that I made some mistakes...feel free to reopen if you find something that needs fixing.

**Comment by WeeknightMVP** [comment]
A good start.

In general, the "layer cake" is a nested digraph comprising a layer of labs and a layer of components within each lab, with a critical path over some components of multiple labs and a recommended path over all components within each lab.  Presently, the critical path comprises one component per lab (`Salsa20` is the only critical lab with an extra, non-critical component, `Salsa20Props`).

More specifically,
  * "Previous Lab" and "Next Lab" should navigate along the critical path
  * "More" should link a critical lab component to representative entry components of optional labs
  * "Up" should link each non-critical component (entry or otherwise) back to the critical component that linked to its representative   
  * "Previous Component" and "Next Component" should navigate a recommended path of all components in the current lab
  * Each lab component with an `**EXERCISE** should have a corresponding "Answers" file and link, 
  * Each "Answers" file should have a link back to the "Exercises" it answers
  * The nested graph of "Answers" should mirror that of the corresponding "Exercises".

If we're up for some...exercise, we could depict recommended paths graphically within each multi-component lab and/or check the consistency of navigation in a CI script using metadata.

**Comment by weaversa** [comment]
Thanks for having another go @WeeknightMVP. If you make a PR I will help out.
