### ISSUE TITLE
`SimonSpeck.md` typo/inconsistency: `constraint` vs `constraints`

### ISSUE THREAD

**Issue by dfu-github** [weaversa/cryptol-course#161]
In `SimonSpeck.md`, lines 181-192:
```
parameter
  
  type n : #    // word size
  type m : #    // words in key
  type T : #    // rounds in the key schedule
  type j : #    // index of z-sequence used (i.e. use sequence z_j)
  type constraint ( fin n, fin m, fin T, fin j
                  , 16 <= n, n <= 64
				  ,  2 <= m, m <= 4
				  ,  0 <= j, j <= 4
				  , 32 <= T, T <= 72
				  )

```
But in lines  212-215 we have:
```
We are also able to specify general type constraints for these
parameters. The line that begins `type constraints` places some
general bounds on the ranges of values that are possible for each
parameter.
```

The code "compiles" if I change `type constraint` to `type constraints`, so I assume both are legal, and Cryptol does not distinguish the number of constraints. In any case, either the code should be changed to `constraints` or the following comment should be changed to `constraint`.

**Comment by weaversa** [comment]
`type constraints` also works? Sounds like lazy parsing...does `type constraintHappyBirthday’ work as well?

**Comment by dfu-github** [comment]
Hello Sean,

I don't know about `type constraintHappyBirthday`, but `type
constraintHAPPYBIRTHDAY` worked fine. 😁

In any case, I only saw `type constraint` in the Speck spec, so I'm
guessing that's the "right" thing?

--David

**Comment by weaversa** [comment]
Yes, it should be `type constraint`
