### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#166]
With github.io and the new layercake for labs, it might be worth attempting to make a website version of the course.

**Comment by WeeknightMVP** [comment]
Pros...
- HTML 5 defines `<detail>`/`<summary>` tags, which we could use for exercise solutions and hints on the same HTML page.
- The Cryptol build includes a `cryptol-html` utility that generates syntax-highlighted `<pre>` blocks from native Cryptol.

...and cons...
- The REPL (via `Unlit.hs`) does not currently extract Cryptol code from HTML.

**Comment by weaversa** [comment]
1. Fix relative linking for layercake.
2. change spaces to dashes for all codeblock identifiers
    * rebuild the ci script (scripts/extract_snippets) to use hyphened identifiers.
