### ISSUE TITLE
Bibliography links

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#168]
They should be made clickable:

See: https://weaversa.github.io/cryptol-course/labs/CRC/CRC.html

**Comment by weaversa** [comment]
Github markdown can automatically linkify text starting with http. github.io doesn't do this, so we need to do `[]()` for all links (not just bibliographies).

**Comment by WeeknightMVP** [comment]
Such sections should also be labeled consistently (e.g. vs. `References` in `KeyWrapping.md`).

**Comment by weaversa** [comment]
I fixed the CRC ones. If we find anymore, let's open another ticket.
