### ISSUE TITLE
gitpod.io

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#171]
I created a .yml file.

Try it out here: https://gitpod.io/#github.com/weaversa/cryptol-course

We should add the VS Code extensions and update the installation instructions. I think this will be the preferred way to take the course. It's so easy!

Thoughts?

**Comment by weaversa** [comment]
I added the pdf extension, had the README file open automatically, and started Cryptol (with some help text) in the terminal.

**Comment by emlisa3162** [comment]
I'm a heavy gitpod user esp. for cryptol dev so it was quite nice to see it included here!
