### ISSUE TITLE
Update to 2.12

### ISSUE THREAD

**Issue by michaelabernardo** [weaversa/cryptol-course#173]
The use of `undefined` changed in one of the newer versions of Cryptol. We need to update the labs so they'll load appropriately with this version. 

```
Cryptol::error called at Cryptol:967:13--967:18
Cryptol::undefined called at /workspace/cryptol-course/labs/CRC/CRC.md:118:14--118:23
labs::CRC::CRC::CRCSimple called at /workspace/cryptol-course/labs/CRC/CRC.md:125:26--125:35
(Cryptol::==) called at /workspace/cryptol-course/labs/CRC/CRC.md:125:26--125:63
```

**Comment by weaversa** [comment]
I rolled the gitpod back to 2.10. We'll need to check over the whole course before we move to 2.11. I'm changing the name of this ticket to reflect that.

**Comment by weaversa** [comment]
I updated some things and it seems to work fine. If I missed something, anyone is free to make an issue and we'll fix it.
