### ISSUE TITLE
Bit twiddling

### ISSUE THREAD

**Issue by benjaminjellison** [weaversa/cryptol-course#19]
Do you guys want me to create a branch with my bit twiddling exercises?  I put it in the `cryptol-saw-course` git a while ago on gitlab.  I think it's a pretty good intro to SAW (it assumes someone is at least familiar with Cryptol).

**Comment by weaversa** [comment]
Yes

**Comment by weaversa** [comment]
Beat you to it! https://github.com/weaversa/cryptol-course/pull/20

**Comment by weaversa** [comment]
Are you willing to polish them up?

**Comment by benjaminjellison** [comment]
Fixed the name of the Cryptol answers file, as well as changing the solver to z3.
