### ISSUE TITLE
Typo in Language Basics Lab

### ISSUE THREAD

**Issue by shanth2600** [weaversa/cryptol-course#196]
In the `Types of Variables` section, the following line:
`There are 2^n values of type [n]. There are 2^mn values of type [m][n], etc.` 
should be
`There are 2^n values of type [n]. There are 2^m+n values of type [m][n], etc.`

**Comment by weaversa** [comment]
On second thought, it should be `2^mn`. For example, type `[2][8]` means we have two sequences, each of 8-bits, for a total of 16 bits. 16 bits can take on `2^16 == 65536` possible values.
