### ISSUE TITLE
Pages failing

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#203]
https://github.com/weaversa/cryptol-course/runs/6719289492?check_suite_focus=true#step:4:213

Ummm...@WeeknightMVP, seems some triple quoting double curly braces etc. is mucking up the html render. Any ideas?

**Comment by weaversa** [comment]
specifically here:

```python
self.points_to(player, cry_f("""{{ name = repeat 0x41 : [{MAX_NAME_LENGTH}][8],
                                   level = 1 : [32],
                                   hp = 10 : [32],
                                   atk = 5 : [32],
                                   def = 4 : [32],
                                   spd = 3 : [32] }}"""))
```

**Comment by WeeknightMVP** [comment]
Maybe try wrapping fenced code blocks with conflicting (`{{ ... }}` or `{% ... %}`) syntax in `{% raw %} ... {% endraw %}` or `{% highlight %} ... {% endhighlight %}` tags?

**Comment by weaversa** [comment]
Funny thing, the code block one or two above the broken one looks almost identical and works fine!

**Comment by weaversa** [comment]
@WeeknightMVP your `{% raw %}` idea worked. The second issue is was the "click here" hidden text block. I removed it and now everything seems good.
