### ISSUE TITLE
Path missing from saw-remote-api example call.

### ISSUE THREAD

**Issue by Yobaranous** [weaversa/cryptol-course#207]
Following issue seen when running SAW lab in gitpod.io.
When running the example command "saw-remote-api http --host 0.0.0.0 --port 36691 &", received the error "Missing PATH".

**Comment by weaversa** [comment]
Great catch @Yobaranous! We were missing a `/`. The full command should be:

```
saw-remote-api http --host 0.0.0.0 --port 36691 / &
```
