### ISSUE TITLE
Add GHCR container for Cryptol 2.13

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#213]
@weaversa Could you add a container tagged `ghcr.io/weaversa/cryptol-course:2.13`? Now that Cryptol 2.13's Python API supports `check`, `safe`, and other commands, and corrects `W4_ABC` and `W4_ANY` to refer to the correct solvers, we shouldn't need adapters to work around these any more. (We can keep a generic "run a command and exit on failure" that works for any of the `Connection` commands.)

**Comment by weaversa** [comment]
The 2.12 is a bit of a misnomer. We've just been using the nightlies. I've rerun the builds and we will soon have the 2.13 nightly.

**Comment by WeeknightMVP** [comment]
Oh, well that explains why the new things work...

**Comment by weaversa** [comment]
Also updated the gitpod tag.
