### ISSUE TITLE
Newcomer SAW Section

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#218]
From a conversation with @dylanmc ---

It would be nice to have a section in the SAW lab that's for newcomers. When first learning SAW, the use of all of the different languages - C, Cryptol, SAWScript, and Python, can be pretty intimidating. It's fine to have them all, but in the really intro stuff, it would be helpful first to acknowledge that this is challenging, and (for example) for the first few occurrences in the examples to add comments in the Python code when a String contains a Cryptol spec. The tables that break those lines down are great, but students can get stuck trying to figure out the code before realizing the explanation is below.

Perhaps there should also be some lengthy exposition (right up front) that goes over the process of using Python and SAW to compare Cryptol to C, some use cases, and what the value is to using this technology.

**Comment by djmorel** [comment]
That's a very good point. There are lot of pieces in play, and a bird's-eye view of everything would help make things clearer.

I can write an intro section that goes over the SAW orchestra (source code, SAW, & Cryptol) and scripting flavors (SAWScript & Python).

**Comment by djmorel** [comment]
@weaversa I finally got something started up for the newcomer section.

Would we also want a version of the newcomer section in [Overview.md](https://github.com/weaversa/cryptol-course/blob/master/labs/Overview/Overview.md) given that the course's `README` suggests it is both a Cryptol and SAW overview?
