### ISSUE TITLE
Common Error Messages (Lab)

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#23]
@jdwoolc We can continue the discussion here needed.

**Comment by benjaminjellison** [comment]
Here's a common error (doesn't have to be an `Integer`:
```
Not a monomorphic type:
{a} a -> Integer -> Bit
```

**Comment by weaversa** [comment]
I did add some examples of errors in the language lab. Let's close this for now and reopen if we find folks are having trouble.
