### ISSUE TITLE
Failed image deployment

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#238]
A [recent PR](https://github.com/weaversa/cryptol-course/pull/235) went through, but [refused](https://github.com/weaversa/cryptol-course/actions/runs/11601267304/job/32303594433#step:5:9336) to update the container image on GHCR.  Is this a restriction on which user triggers deployment?

**Comment by weaversa** [comment]
GitHub is strange with updating containers. Sometimes I just run it a bunch
of times until it works...or delete the old tag and run it
again...eventually it works but I don't ever have a good sense of why.

**Comment by weaversa** [comment]
got it!
