### ISSUE TITLE
Installation and lazy user shortcuts

### ISSUE THREAD

**Issue by AssemblyZig** [weaversa/cryptol-course#31]
Observations as a neophyte
- The nightly builds for Cryptol have specific OS version names (e.g., Ubuntu 14.04); initial testing has it working fine on Ubuntu 18.04
- z3 is available for "apt install" under U18.04 -- but you get version 4.4.1, which doesn't support the needs of Cryptol (fails with "unknown parameter" issue)
     - Upon building/installing a newer z3, the directory should be added to the front of the PATH variable, so that it can overshadow any past misdeeds.

**Comment by michaelabernardo** [comment]
The Cryptol GitHub mentions for Macs that:  
- On Mac OS X, Cryptol is also available via Homebrew (https://brew.sh/). Simply run `brew update && brew install cryptol` to get the latest stable version.

This was really easy and helpful for me! Docker was also easy as suggested in Option 1

**Comment by weaversa** [comment]
We should also mention that ‘apt’ has old versions of z3 and Cryptol, both of which are out of date and won’t be compatible with the course (though, I don’t know that for sure).

**Comment by AssemblyZig** [comment]
The apt z3 is definitely incompatible.  And it's reasonable/appropriate to expect the students to get the latest rendition of the TUT (tool under test).  I'll tweak the install.md to those ends and submit a pull request.

**Comment by WeeknightMVP** [comment]
Current [Docker Run](https://docs.docker.com/engine/reference/commandline/run/#add-bind-mounts-or-volumes-using-the---mount-flag) documentation recommends using `--mount` rather than `-v`:

> Even though there is no plan to deprecate `--volume`, usage of `--mount` is recommended.

The boilerplate I added to the `Demos` modules applies this recommendation, but we should decide whether to incorporate it into `INSTALL.md`.
