### ISSUE TITLE
Suggested Boilerplate for Loading File

### ISSUE THREAD

**Issue by michaelabernardo** [weaversa/cryptol-course#43]
[boilerplate.txt](https://github.com/weaversa/cryptol-course/files/4788843/boilerplate.txt)

To load this document into Cryptol, open a terminal (Linux), command prompt (Windows), or Cryptol image (Docker) from your `cryptol-course` directory.

```sh
> cryptol labs/Demos/OneTimePad.cry
...
Loading module Cryptol
Loading module labs::Demos::OneTimePad
labs::Demos::OneTimePad>
```

Alternatively, you can use the `:m` or `:l` command from within Cryptol to load this document. (To avoid errors, make sure Cryptol was started in the `cryptol-course` directory).

```sh
Cryptol> :m labs::Demos::OneTimePad
Loading module labs::Demos::OneTimePad
labs::Demos::OneTimePad>
```

**Comment by michaelabernardo** [comment]
Later labs could probably just include something like this after the sentence about it being a literal Cryptol Document :

To load this file into Cryptol, type `:m labs::Demos::OneTimePad` in your running Cryptol Interpreter.

**Comment by WeeknightMVP** [comment]
@michaelabernardo This looks pretty good to me, assuming it follows the sentence linking to installation instructions.

**Comment by WeeknightMVP** [comment]
@michaelabernardo I've created a [`demos-boilerplate`](https://github.com/weaversa/cryptol-course/tree/demos-boilerplate) branch presenting usage instructions for each demo.  It's pretty repetitive, but hopefully clear and correct for Linux and Windows, local or Docker. I'll defer to the experts for other platforms.

**Comment by weaversa** [comment]
@jpziegler  created a new docker image For Cryptol that has abc, yices, etc installed. Let’s use that one.

**Comment by weaversa** [comment]
Try this: docker pull cryptolcourse/cryptol

**Comment by weaversa** [comment]
We should update the INSTALLmd as well

**Comment by WeeknightMVP** [comment]
I have updated the Docker instructions to use `cryptolcourse/cryptol` but retain `--mount` and `--env` options.  Should some of the labs and specs be added to this Docker image?

**Comment by jdwoolc** [comment]
I think we've factored the installation instructions into an INSTALL.md file -- the boiler plate for the demos could probably just be pointers to that, now, right?

**Comment by weaversa** [comment]
> Should some of the labs and specs be added to this Docker image?

People will want to edit the labs...I’m worried that having a copy inside the docker image will cause issues with people wanting to use their editor of choice - what if a student wants to do edits on their own fork of the repo, can they still use —mount and —env? It seems like they’d suddenly have 2 copies of the repo in the container and things could get confused.

**Comment by weaversa** [comment]
> I think we've factored the installation instructions into an INSTALL.md file -- the boiler plate for the demos could probably just be pointers to that, now, right?

Yes...the boilerplate should be condensed.
