### ISSUE TITLE
Literate Workflow

### ISSUE THREAD

**Issue by jdwoolc** [weaversa/cryptol-course#46]
This may be addressed somewhere I haven't seen yet, but it might be helpful, possibly in the Overview, what the intended workflow is for the exercises. Just spell out something like:

  * Load the module in cryptol
  * Read through the material -- when you come to an exercise fix it inline
  * Reload the module
  * Check your work -- many exercises are coupled with properties to test to make sure you have the correct answer

And we could have the student just do that with something easy. Maybe this could go right after the HelloWorld example, or at the beginning of the first lab that's hands-on.

**Comment by weaversa** [comment]
The flow should go in the initial README.md. As well as maybe in the boilerplate in each markdown file? See Issue #43 and PR #44.

**Comment by jdwoolc** [comment]
I made a new branch called flow-tweaks and it looks like we have this covered there.
