### ISSUE TITLE
Redudant Installation Instructions

### ISSUE THREAD

**Issue by jdwoolc** [weaversa/cryptol-course#48]
I'm starting to take a look at the material "overall". There is an INSTALL.md file at the top level directory and there are fairly verbose installation instructions at the beginning of each of the Demos.

Given that maintaining similar information in two locations is a challenge I think we should consolidate...

There should just be a simple link back to the INSTALL.md file there, no?

**Comment by weaversa** [comment]
Those aren’t install instructions, those commands show how to load each demo into cryptol using docker

**Comment by weaversa** [comment]
Those instructions should be in the install.md. It’s great to see how to properly load a module for each OS/install path.

**Comment by weaversa** [comment]
#47 add "run the interpreter" instructions to the INSTALL.md. We can remove (@WeeknightMVP) the run instructions from the demos and add a boilerplate sentence about going through the install instructions before trying the labs.
