### ISSUE TITLE
Switch to cryptolcourse/saw

### ISSUE THREAD

**Issue by jpziegler** [weaversa/cryptol-course#51]
I added the additional solvers to the saw Docker image on Dockerhub:

https://hub.docker.com/repository/docker/cryptolcourse/saw

Consider changing Docker instructions for SAW to this.

**Comment by weaversa** [comment]
Oh great! Someone should definitely update the instructions...someone...anyone?

**Comment by weaversa** [comment]
[INSTALL.md](INSTALL.md) needs updating with @jpziegler's Cryptol and SAW containers.

**Comment by weaversa** [comment]
Best to do it on PR #47 atm.

**Comment by weaversa** [comment]
I made the change in #47
