### ISSUE TITLE
Docker image produces incorrect counterexample for (underspecified) `CryptoProofs` Exercise `2.5.1`

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#59]
```sh
$ docker run --read-only --rm --mount type=bind,src=$(pwd),dst=/mnt/cryptol-course --env CRYPTOLPATH=/mnt/cryptol-course -it cryptolcourse/cryptol
labs::CryptoProofs::CryptoProofs> :s prover=abc
labs::CryptoProofs::CryptoProofs> :sat \(k, k', pt) -> DES.encrypt k pt == DES.encrypt k' pt
```
Note: I am aware that this neglects the key equality check `k != k'`.
```sh
...
(\(k, k', pt) -> DES.encrypt k pt == DES.encrypt k' pt)
  (0x9980b66c166b6dff, 0x89d989038e1cab20, 0xf1bc73da96a4873d) = True
labs::CryptoProofs::CryptoProofs> let (k, k', pt) = it.arg1
labs::CryptoProofs::CryptoProofs> (k, k', pt)
(0x9980b66c166b6dff, 0x89d989038e1cab20, 0xf1bc73da96a4873d)
labs::CryptoProofs::CryptoProofs> DES.encrypt k pt == DES.encrypt k' pt
False
```
?!?!

**Comment by weaversa** [comment]
The abc developer doesn’t track cryptol, and Cryptol doesn’t track abc...try the proof using the abc in saw. This is likely the abc version in the docker container is out of wack with Cryptol.

**Comment by weaversa** [comment]
To fix, we can dump the smtlib file for the command (using the offline prover) and submit a bug to abc’s github page.

**Comment by WeeknightMVP** [comment]
@weaversa I don't see anything about offline smtlib dumps, so defer to you. It would be good to know how to do this, though...

**Comment by weaversa** [comment]
```
labs::CryptoProofs::CryptoProofs> :s prover=
Prover must be cvc4, yices, z3, boolector, mathsat, abc, offline, any, sbv-cvc4, sbv-yices, sbv-z3, sbv-boolector, sbv-mathsat, sbv-abc, sbv-offline, sbv-any, w4-cvc4, w4-yices, w4-z3, w4-boolector, or w4-offline
```

If you set prover to `offline` it will produce an smtlib file.

**Comment by weaversa** [comment]
I was wrong...it doesn't produce a file, just dumps the file to stdout. we have to use -c options to capture the file.

**Comment by weaversa** [comment]
I generated the smtlib and sent the example to Alan.

**Comment by weaversa** [comment]
Maybe we could fill in the first part of the exercise to avoid this spurious counterexample?

:sat \(k, k', pt) -> k!= k’ ==> undefined

**Comment by weaversa** [comment]
Fixed --
See: https://github.com/berkeley-abc/abc/commit/322cea8234aaa6a46c3f2f19c3c3246476231875

@jpziegler Will you update the cryptol and docker contains to use the just-fixed abc?

**Comment by weaversa** [comment]
oh hold on...still something not working...

**Comment by weaversa** [comment]
Ok! @jpziegler 
I verified that the latest version of abc as built from github works.

```
cryptol-course]$ cryptol labs/CryptoProofs/CryptoProofs.md 
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.8.1 (e914cef)
https://cryptol.net  :? for help

Loading module Cryptol
Loading module specs::Primitive::Symmetric::Cipher::Block::Cipher
Loading module specs::Primitive::Symmetric::Cipher::Block::DES
Loading module labs::CryptoProofs::CryptoProofs
labs::CryptoProofs::CryptoProofs> :s prover=abc
labs::CryptoProofs::CryptoProofs> :sat \(k, k', pt) -> DES.encrypt k pt == DES.encrypt k' pt 
(\(k, k', pt) -> DES.encrypt k pt == DES.encrypt k' pt)
  (0x0000000000000000, 0x0000000000000000, 0x0000000000000000) = True
(Total Elapsed Time: 4.957s, using "ABC")

```
