### ISSUE TITLE
Minor Issues -- Language Features

### ISSUE THREAD

**Issue by jdwoolc** [weaversa/cryptol-course#61]
Markdown in Github doesn't render links that are broken across lines correctly, these links are "broken":
* [curried] (https://en.wikipedia.org/wiki/Currying)
* [partial application] (https://en.wikipedia.org/wiki/Partial_application)
* [lazy] (https://en.wikipedia.org/wiki/Lazy_evaluation) 

We should discuss how to format the markdown if we really want to try to enforce an 80-character width.

There appear to be typos in the text with these phrases:
* "If he helps you, mentally..."

**Comment by weaversa** [comment]
The 80-character width is really just for Cryptol style. It doesn't need to apply for Markdown. It just so happens that Meta-q in Emacs will occasionally break these links.

**Comment by weaversa** [comment]
It looks like Frank made these fixes.
