### ISSUE TITLE
CRYPTOLPATH issue

### ISSUE THREAD

**Issue by AssemblyZig** [weaversa/cryptol-course#62]
This is probably a Galois issue; let me know.

BLUF:  subdirectories get dropped in seeking files via CRYPTOLPATH

$ echo $CRYPTOLPATH
CRYPTOLPATH=/home/jlziegl/repos/cryptol-course

\# from a different directory ($HOME in this case) invoke cryptol
$ strace -f cryptol 2> /tmp/cryptolrun
Cryptol> :load README.md    # success!
Cryptol> :load labs/LanguageBasics/LanguageBasics.md
[error] can't find file: LanguageBasics.md

\# In the strace results....
[pid  7787] stat("labs/LanguageBasics/LanguageBasics.md", 0x42003e24f0) = -1 ENOENT (No such file or directory)
[pid  7787] stat("/home/jlziegl/repos/cryptol-course/LanguageBasics.md", 0x42003e2690) = -1 ENOENT (No such file or directory)
[pid  7787] stat("/home/jlziegl/LanguageBasics.md", 0x42003e2880) = -1 ENOENT (No such file or directory)
[pid  7787] stat("/home/jlziegl/.cryptol/LanguageBasics.md", 0x42003e2a00) = -1 ENOENT (No such file or directory)
[pid  7787] stat("/home/jlziegl/repos/galois/saw-0.4.0.99-2020-06-09-Ubuntu14.04-64/share/cryptol/LanguageBasics.md", 0x42003e2ba0) = -1 ENOENT (No such file or directory)

Looks like the second search is $CRYPTOLPATH/`basename PARAMETER`

**Comment by weaversa** [comment]
Yeah, the CRYPTOLPATH is for loading modules, not files. So, use :m. 
Maybe we could encourage :m over :l everywhere?

**Comment by weaversa** [comment]
Well, actually the strace makes it seem like it _could_ work. I’ll submit a ticket.

**Comment by jdwoolc** [comment]
Is tab completion for :m commands a non-starter? I was wishing we had that too working through and testing pieces here.

**Comment by weaversa** [comment]
On second thought, how’s cryptol supposed to know if you want to load a file from your current path? What if both were valid? What Cryptol does now is likely the correct behavior

**Comment by weaversa** [comment]
> Is tab completion for :m commands a non-starter? I was wishing we had that too working through and testing pieces here.

That could be a ticket!

**Comment by AssemblyZig** [comment]
Looking at the results in the strace, it appears to try the current directory first, so I think that's covered.

**Comment by AssemblyZig** [comment]
The [Cryptol programming manual](https://cryptol.net/files/ProgrammingCryptol.pdf) is rather, ehrm, sparse and cryptic about :m(odule)...
> **Loading a module** At the Cryptol prompt you can load a module by name with the :module command.
So, what is a module's "name"?  My (likely ham-fisted) attempts to use :m have been fruitless.

**Comment by weaversa** [comment]
Really?

We put boilerplate at the top of EVERY lab that includes how to load the lab as a module.

**Comment by weaversa** [comment]
For example:

# Introduction

This lab is a [literate](https://en.wikipedia.org/wiki/Literate_programming) 
Cryptol document --- that is, it can be loaded directly into the Cryptol
interpreter. Load this module from within the Cryptol interpreter running
in the `cryptol-course` directory with:

```shell
cryptol> :m labs::CRC::CRC
```

We start by defining a new module for this lab:

```
module labs::CRC::CRC where
```

...

**Comment by weaversa** [comment]
I see...every lab except the language features lab. 🤦‍♂️

**Comment by AssemblyZig** [comment]
Remember, I am the epitome of the ignorant student.  :-P 

Observations:
* :module doesn't like the extension in the name
* One can do a hackneyed tab completion for :module by using '/' characters, remove the .md from the end, and changing '/'s to "::"s
* :module is finicky
``` 
Cryptol> :! cat zigplay/problem9.cry
sqr : Integer -> Integer
sqr a = a^^2 

match : Integer -> Integer -> Integer -> Bit
match a b c =
  ((sqr a + sqr b == sqr c) /\ (a + b + c == 1000) /\ (a < b) /\ (b < c))
Cryptol> :module zigplay::problem9
Loading module Main

[error] :1:1--1:1:
    File name does not match module name:
    Saw: Main
    Expected: zigplay::problem9
```
* :load seems to provide the same functionality with greater versatility.

School me, please....

**Comment by weaversa** [comment]
add

module zigplay::problem9 where

To the top of the file

**Comment by weaversa** [comment]
Consider page 12 — https://github.com/GaloisInc/cryptol/blob/master/docs/Syntax.pdf

**Comment by AssemblyZig** [comment]
FTR: it appears that the :module search order is .cry, .tex, .markdown, .md.  

So, if :load results in the same outcome as :module and has more flexibility (tab completion, explicit suffix determination), why use :module?

**Comment by weaversa** [comment]
> FTR: it appears that the :module search order is .cry, .tex, .markdown, .md.
> 
> So, if :load results in the same outcome as :module and has more flexibility (tab completion, explicit suffix determination), why use :module?

If you want to create a one-off Cryptol specification that noone will ever reuse, a moduleless .cry file is fine.

Adding the module line allows other Cryptol specifications to import and make use of the definitions in the module, similar to #include in C. Modules can have parameters and private definitions.

See this SHA specification for an example of a parameterized module: https://github.com/GaloisInc/cryptol-specs/blob/master/Primitive/Keyless/Hash/SHA.cry

And see this SHA-256 and SHA-512 specifications which are instantiations of that module: 
https://github.com/GaloisInc/cryptol-specs/blob/master/Primitive/Keyless/Hash/SHA256.cry
https://github.com/GaloisInc/cryptol-specs/blob/master/Primitive/Keyless/Hash/SHA512.cry

**Comment by weaversa** [comment]
Also, I think `:module` allows one to instantiate a parameterized module with concrete parameters.

**Comment by jdwoolc** [comment]
I think that last comment might be the key difference -- I think it's functionality we're not using. We've traded off `:l` tab-completion for the unexercised option of using concrete module parameters.

**Comment by weaversa** [comment]
Well, and like you said earlier, modules load correctly no matter what your current directory is.

**Comment by AssemblyZig** [comment]
Regarding the topic of this issue:  it appears that CRYPTOLPATH does not work as (I) expected.  The example in Interpreter.md shows cryptol being invoked in the base directory.  If it is invoked elsewhere, the sample lab does not load or module (when did "module" become an action verb?).

**Comment by weaversa** [comment]
It's one or the other. If CRYPTOLPATH is set correctly, you can invoke cryptol from anywhere and use `:m` to access all of the labs.

**Comment by weaversa** [comment]
If you don't set CRYPTOLPATH, you'll need to park in the root when running cryptol.

**Comment by weaversa** [comment]
Try this --- cd to labs/Salsa20 and ":l Salsa20Props.md"

**Comment by AssemblyZig** [comment]
More exploration: :module appears to leverage CRYPTOLPATH correctly, :load doesn't.

> Cryptol> :! pwd
/home/jlziegl
Cryptol> :! echo $CRYPTOLPATH
repos/cryptol-course/
Cryptol> :m labs::Demos::Sudoku
Loading module labs::Demos::Sudoku
labs::Demos::Sudoku> :l labs/Demos/Sudoku.md
[error] can't find file: Sudoku.md
Cryptol>

**Comment by AssemblyZig** [comment]
Note that :load does use CRYPTOLPATH somewhat, just not if there is more directory stuff going

> Cryptol> :l README.md
Loading module Cryptol
Loading module Main
Main>

**Comment by weaversa** [comment]
That is weird…I put in a ticket.
