### ISSUE TITLE
Class structure

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#7]
The flow we have (in the README.md) is a good start, but I think it needs to primarily support distance learning --- i don't believe we'll be teaching this in a classroom environment anymore. More likely people will take the course on their own time. Any suggestions?

-----
## Suggested Flow

1. [Introduction](intro.md)
   Learn about Cryptol and SAW.
2. [Installation](labs/install.md)
   Get up and running.
3. [Demos](labs/Demos/Demos.md)
   Behold the possibilities.
4. [Basics](labs/interpreter/interpreter.md)
   Cut your teeth on the easy stuff.
5. [Salsa20](labs/Salsa20/Salsa20.md)
   Pass an encrypted stream.

## Advanced topics
- SAW
- crux, argo, etc.
-----

**Comment by WeeknightMVP** [comment]
What would it take to establish an online interpreter?  I've seen similar examples for [Haskell](https://repl.it/languages/haskell) and [Coq](https://math-comp.github.io/mcb/ch3.html).

**Comment by weaversa** [comment]
These folks did it: https://tio.run/#cryptol

**Comment by WeeknightMVP** [comment]
That's...a decent demo that run interactive Cryptol, but not...OK, I suppose I said "interpreter".

s/interpreter/IDE supporting the multi-file workflows to be presented in the course

But thank you for introducing me to TIO.

**Comment by weaversa** [comment]
I just found out that Cryptol can parse Markdown. Perhaps we do all the guided labs using Markdown as a literate substitute for LaTeX.

**Comment by WeeknightMVP** [comment]
Let's give it a shot.

**Comment by weaversa** [comment]
@WeeknightMVP Captured your flow here.

**Comment by AssemblyZig** [comment]
Current collection of content:
Glue:
Interpreter, language-basics (branch, "cheese"), style-guide (branch)
Demos:
Caesar, NQueens, OTP, Sudoku,WHSudoku(?)
Labs:
CRC, cryptoproofs  (branch), Salsa20, projecteuler (branch),
LorumIpsum (branch simple-spec), saw/bittwiddling, saw/arithmetic-verification (branch),
NIST keywrapping (branch)
Misc: 
padding (branch),

Also noted that this is addressed in https://github.com/weaversa/cryptol-course/issues/3 to some degree.
