### ISSUE TITLE
Parameterized Modules (lab)

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#70]
Show Simon, have students write Speck.

**Comment by weaversa** [comment]
I think we’re getting close - https://github.com/weaversa/cryptol-course/tree/lab-SimonSpeck

**Comment by jdwoolc** [comment]
Yeah! Simon is looking pretty good. The markdown is just a stub. I might get ambitious this weekend with the exposition.

What do you think we do with Speck? Package it up a d hide it away? I'd appreciate it @weaversa took a look at cleaning up the code.

**Comment by WeeknightMVP** [comment]
For kicks and giggles, I looked into other lightweight block ciphers and attempted a parameterized Cryptol spec for [TWINE](https://www.nec.com/en/global/rd/tg/code/symenc/pdf/twine_LC11.pdf).  Once again, I'm left wondering whether I've used parameterized modules as intended.  With all the definitions needed in common, what does parameterization really accomplish?

[TWINE.zip](https://github.com/weaversa/cryptol-course/files/4867120/TWINE.zip)

**Comment by WeeknightMVP** [comment]
OK, the `TWINE` branch is ready for...some sort of consideration. Right now it reads as a case study on the misappropriation of parameterized modules, perhaps conveying some insights to experienced Cryptol developers and users, but confusing new students for whom a simpler introduction like `lab-SimonSpeck` would be better suited.

**Comment by WeeknightMVP** [comment]
As [the paper on module parameters](https://github.com/GaloisInc/cryptol/blob/master/docs/AbstractValuesAndModuleParameters.md) points out, this might be a reasonable lab in which to mention `newtype` as a way to encapsulate a complex data structure.

Consider, for example, an abstract block cipher:

```Cryptol
module XORCipher where

type Op Key Block = Key -> Block -> Block

newtype BlockCipher Key Block = { encrypt: Op Key Block, decrypt: Op Key Block }
type constraint is_BlockCipher /* Key */ Block = Cmp Block
```

`newtype` establishes both a type and a constructor:

```sh
Cryptol>:m XORCipher
Loading module XORCipher
XORCipher> :h BlockCipher

    newtype BlockCipher Block Key
    BlockCipher : {Block, Key}
                    {decrypt : Op Key Block,
                     encrypt : Op Key Block} -> BlockCipher Block Key

type/record encapsulation

            ---------
```

One can work with this abstract block cipher by specializing it, for example with an XOR cipher:

```Cryptol
type XORCipher KeyBlock = BlockCipher KeyBlock KeyBlock
type constraint is_XORCipher KeyBlock = (is_BlockCipher /* KeyBlock */ KeyBlock, Logic KeyBlock)

XORCipher:
    {KeyBlock}
    is_XORCipher KeyBlock =>
    XORCipher KeyBlock
XORCipher = BlockCipher { encrypt = (^), decrypt = (^) }
```

This establishes a similar type/constructor pair `XORCipher`, which takes a single type parameter for key/block size, populating parameters for a `BlockCipher` accordingly:

```sh
XORCipher>:h XORCipher

    type XORCipher KeyBlock = BlockCipher KeyBlock KeyBlock

            ---------

    XORCipher : {KeyBlock} (is_BlockCipher KeyBlock, Logic KeyBlock) =>
                  XORCipher KeyBlock

XORCipher>(XORCipher`{[32]}).encrypt 0xDEADBEEF 0xBADDECAF
0x64705240
```

Finally, this type/constructor can be specialized for XOR ciphers of a given key/block size:

```Cryptol
type XORCipher32 = XORCipher [32]

XORCipher32 : XORCipher32
XORCipher32 = XORCipher`{[32]}
```

```sh
XORCipher>:h XORCipher32

    type XORCipher32 = XORCipher [32]

            ---------

    XORCipher32 : XORCipher32

XORCipher>XORCipher32.encrypt 0xDEADBEEF 0xBADDECAF
0x64705240
```

To do next: produce recovery and injectivity properties based on this structure, and specify an abstract CBC mode that takes any such block cipher...

**Comment by WeeknightMVP** [comment]
I noticed that `README.md` now links to the document originally proposing parameterized modules.  The current implementation is subject to imminent change as laid out in Issue [#815](https://github.com/GaloisInc/cryptol/issues/815).

**Comment by weaversa** [comment]
Well, 2.9 comes out in two weeks, and we’ll stick with that until the next release (which could be a year from now). This is something to remember to update once the next next release comes out. Perhaps if the module system info is in Galois’s programming guide, we can leave out the link altogether.

**Comment by weaversa** [comment]
Also, the module system, as we would demonstrate in a lab, isn’t going to change. This is an intro course, so the basic import, private, and parameter commands are all we need here.

**Comment by weaversa** [comment]
merging pr #87 closes this.
