### ISSUE TITLE
specs directory structure

### ISSUE THREAD

**Issue by weaversa** [weaversa/cryptol-course#8]
I don't believe the class here will have enough Cryptol specifications to warrant a complex directory structure like the one from `cryptol-specs`. I'd rather leave the structure simple so students can easily find the specifications.

One proposal is that we place each lab/lecture into its own directory, and all corresponding cryptol specs get placed there. So, if you're doing a lab, everything needed for that lab is in one place. About sharing between labs: we could also allow import statements for modules from previous labs.

Other ideas?

**Comment by WeeknightMVP** [comment]
There are different schools of thought on the latter, one of which is exhibited by [Software Foundations](https://softwarefoundations.cis.upenn.edu) (a formal logic and programming course using Coq).  The [Programming Language Foundations](https://softwarefoundations.cis.upenn.edu/plf-current) module, for example, draws upon the previous [Logical Foundations](https://softwarefoundations.cis.upenn.edu/lf-current), but keeps copies of the prior dependencies in its own folder.  This simplifies packaging for individual modules, but becomes redundant over multiple modules and leads to confusion when bringing in prior work (though to be fair, each module in that series comprises many chapters and covers about a semester of collegiate coursework).

Yes, Caesar is too early to overwhelm students with nested modules and crypto taxonomy, but at some point the course should demonstrate how to reuse specs by applying command line and/or environment variables in a realistic folder layout with specs, scripts, source, etc., per lab session.  One way to reuse content from prior labs is via symbolic links to prior content, but their implementation varies by platform.  A sounder approach is to leverage Makefiles or similar dependency management tools.  Let's keep this in mind as the lab sessions are fleshed out.

**Comment by weaversa** [comment]
The Coq course would be a great reference! Something to keep in mind for Windows: symlinks work in git, but FAT doesn’t support them...or so I read.

**Comment by weaversa** [comment]
> the course should demonstrate how to reuse specs by applying command line and/or environment variables in a realistic folder layout with specs, scripts, source, etc.

in pursuit of having the students combine the work in the labs into a larger project, the students could implement CRC, some data tagging, and an encrypt function, then put everything together to make a wrapped key pair. The picture below was done quickly and is likely complete nonsense, but it gives the idea of a high level project to work towards during the class.

![image](https://user-images.githubusercontent.com/7407930/83089058-5d8dc500-a063-11ea-83d2-b65f5f87e1aa.png)

CRC is a one-liner (with pmod and pmult), but we could also teach CRC using LFSRs, and that is good material for learning about sequence comprehensions. Data tagging is comparatively easy, but could be a place to teach join, split, string manipulations, etc. There are plenty of encryption algorithms to specify. And in the end the student gets a reasonably complex project that can compute something pretty neat (if we can find a nice real-world key wrap method).

**Comment by weaversa** [comment]
...well, we did something...
