### ISSUE TITLE
Import Aliasing/Lists

### ISSUE THREAD

**Issue by WeeknightMVP** [weaversa/cryptol-course#88]
It looks like `KeyWrapping` and `SimonSpeck` (and `TWINE`, which doesn't count) are currently the only labs in the entire course that demonstrate import aliasing (`import {module} as {alias}`).  Perhaps this and import lists (`import {module} (as {alias})? (hiding)? ({definitions})`) should be added to `labs/Language/Basics.md` and prerequisites.

_Edit_: Corrected Markdown location
_Edit_: `as {alias}` is optional

**Comment by weaversa** [comment]
Check the ‘language’ branch. We can add it there.

**Comment by WeeknightMVP** [comment]
OK, I've PR'ed (#98) a section on import lists.

**Comment by WeeknightMVP** [comment]
Closed via [branch deletion / direct commit](https://github.com/weaversa/cryptol-course/commit/36c5c8c4079bef03e1dbccb552c42440009ab61e)
