### ISSUE TITLE
Quick Start Instructions

### ISSUE THREAD

**Issue by jdwoolc** [weaversa/cryptol-course#90]
I checked out the Quick Start instructions, things mostly worked fine out of the box -- two minor issues, and some notes:

"Open Workspace" did not work for me, it appears to be looking for a VSCode artifact of some kind, but it doesn't seem to accept the directory or the .vscode directory contained within as a valid target. Instead, simply choosing Explorer -> Open Folder appeared to work as intended.

The Terminal -> Run Task command appears to be pre-populated with the cryptol-docker command -- this is good. I'm not exactly sure what sequence of operations I took, but at some point this command disappeared for me and I was unable to execute cryptol-docker. Suggest restarting VSCode if this occurs, possibly closing and opening the workspace / folder.

Finally, I had Docker already installed, the link appears to be the same place I got my copy installed, though.

**Comment by weaversa** [comment]
Thank you!!! I changed “open workspace“ to “Open...”.
